B-04004 simplify
holochain/elemental-chat-ui pull request #64
Opened 2021-02-26 23:54 UTC by robbiecarlton

2021-03-09 22:27 UTC, zippy commented
Looks great.  Please remember to merge in the build-script changes too!

2021-03-10 04:02 UTC, JettTech requested changes
Overall, looks good.  I did notice that the `updateHandle` functionality isn't working, so let's get that fixed before the merge.  Otherwise, I just left a few non-blocking requests/comments.

2021-03-10 16:06 UTC, robbiecarlton commented on package.json
> +    "hc:agent-1": "holochain-run-dna -p 8888 -i elemental-chat-1 -u kitsune-proxy://CIW6PxKxsPPlcuvUCbMcKwUpaMSmB7kLD8xyyj4mqcw/kitsune-quic/h/165.22.32.11/p/5778/-- ../elemental-chat/elemental-chat.
good call

2021-03-10 18:34 UTC, robbiecarlton commented on src/ElementalChat.vue
> -      'updateHandle',
No, just didn't need the separate "updateHandle" action as we already have `setAgentHandle` mutation

2021-03-10 18:36 UTC, robbiecarlton commented on src/store/__tests__/elementalChat.test.js
> +  entry: { category: 'General', uuid },
I think that would be fine, but I don't think it matters either way so will just leave it as is, unless you feel strongly

2021-03-10 18:38 UTC, robbiecarlton commented on src/store/callZome.js
> +  if (LOG_ZOME_CALLS) {
Yup can do

2021-03-11 19:25 UTC, zippy approved these changes
Woot!

2021-03-11 19:25 UTC, merged